### PR TITLE
Fix Rail Placement Issues

### LINKED ISSUE #426: You can't place rails on hoppers.
Expected Behaviour: Can place rails on hoppers.
Actual Behaviour: You can't place rails on hoppers.

### PR DESCRIPTION
**Pull request by good777LUCKY**
Fix #426 and can't place on upside-down slab or upside-down stairs.

If down block is...
null => false
is Solid (is not transparent) => true
is Hopper => true
is upside-down Slab => true
is upside-down Stairs => true
else => false

### CODE REVIEW

**Comment by good777LUCKY** [comment]
Ready to review

**Comment by joserobjr** [comment]
I'm unable to test in-game right now so I can't change the code until somebody applies and test this change.

!checkCanBePlace(down)
https://github.com/PowerNukkit/PowerNukkit/blob/5d6459a4e16501d81bcd7f4484a542b073375fc7/src/main/java/cn/nukkit/block/BlockRail.java#L71-L81

Replace the `this.down().isTransparent()` with `checkCanBePlace(down())`, and test placing the rail on top of the upsidedown slabs, stairs, and the hopper and then cause a block update by placing any block next to it. It should not drop.

**Comment by good777LUCKY** [comment]
> `onUpdate(int)` also needs to call the new method

I think it is fixed.
Screenshot_2020-08

**Comment by good777LUCKY** [comment]
> `onUpdate(int)` also needs to call the new method

I update it too

**Comment by good777LUCKY** [comment]
Ready to review again

**Comment by good777LUCKY** [comment]
Is there something wrong?

File: src/main/java/cn/nukkit/block/BlockRail.java [hunk 1]
```diff
@@ -142,8 +142,26 @@ public boolean place(Item item, Block block, Block target, BlockFace face, doubl
...
+        if (!check.isTransparent()) {
+            return true;
+        }
+        if (check instanceof BlockHopper) {
+            return true;
+        } else if (check instanceof BlockSlab) {
+            return (check.getDamage() & 0x8) == 0x8;
+        } else if (check instanceof BlockStairs) {
+            return (check.getDamage() & 0x4) == 0x4;
+        }
```
Comment (joserobjr) [inline src/main/java/cn/nukkit/block/BlockRail.java:162]: Please, use the property accessors like `((BlockSlab)check).isOnTop()` and `((BlockStairs)check).isUpsideDown()` instead of magic values

Comment (good777LUCKY) [reply src/main/java/cn/nukkit/block/BlockRail.java]: Thank you

**Comment by good777LUCKY** [comment]
Ready to review again
