### PR TITLE
Fixes all blocks having lava resistance and non-netherite items not burning

### LINKED ISSUE #671: Items don't burn if thrown into lava
# 🐞 I found a bug

### 📸 Screenshots / Videos

https://youtu.be/CHnxXSpvKAM

### ▶ Steps to Reproduce

1. Throw any Item in lava

### ✔ Expected Behavior

Items will burn

### ❌ Actual Behavior

Items swim in lava

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-SNAPSHOT (bc88a5d)
* Debug link: ✍
* Timings link (if relevant): ✍

### LINKED ISSUE #672: Items dont burn if using flint and steel.
# 🐞 I found a bug

### 📸 Screenshots / Videos
https://www.youtube.com/watch?v=_012NIp1jy0&feature=youtu.be

### ✔ Expected Behavior
Burn the items.

### ❌ Actual Behavior
Doesnt burn.

### 📋 Debug information

* PowerNukkit version: https://github.com/PowerNukkit/PowerNukkit/actions/runs/289511776
Nukkit 1.4.0.0-PN-SNAPSHOT (git-bc88a5d) 「PowerNukkit」

### PR DESCRIPTION
**Pull request by Braayy**
Fixes issues #671 and #672 and all item blocks having lava resistance

Closes #671.
Closes #672.

### CODE REVIEW

File: src/main/java/cn/nukkit/entity/item/EntityItem.java [hunk 1]
```diff
@@ -180,8 +180,11 @@ public boolean onUpdate(int currentTick) {
         boolean hasUpdate = this.entityBaseTick(tickDiff);
 
         boolean lavaResistant = item != null && item.isLavaResistant();
-        
-        if (!lavaResistant && isInsideOfFire()) {
```
Comment (RORIdev) [inline src/main/java/cn/nukkit/entity/item/EntityItem.java:184]: The implementation of `Entity#isInsideOfFire` checks if the colliding blocks are an instance of `BlockFire` which includes `BlockFireSoul`.  The removal of it and subsequent usage of a manual local check could lead to harder maintainability, if another fire-like block were to be added in the future.

File: src/main/java/cn/nukkit/entity/item/EntityItem.java [hunk 2]
```diff
@@ -182,7 +182,7 @@ public boolean onUpdate(int currentTick) {
         boolean lavaResistant = item != null && item.isLavaResistant();
 
         int blockId = this.getLevelBlock().getId();
-        boolean insideOfHotBlock = blockId == BlockID.FIRE || blockId == BlockID.LAVA;
+        boolean insideOfHotBlock = blockId == BlockID.FIRE || blockId == BlockID.SOUL_FIRE || blockId == BlockID.LAVA || blockId == BlockID.STILL_LAVA;
```
Comment (RORIdev) [inline src/main/java/cn/nukkit/entity/item/EntityItem.java:185]: Instead of using this manual check consider creating an `isInsideOfLava` function inside of `Entity` that checks if one of the colliding blocks is lava, since `BlockLavaStill` inherits from `BlockLava` and a simple `instanceof BlockLava` could be used to check it.

**Review by RORIdev — CHANGES_REQUESTED** [review]

**Review by RORIdev — APPROVED** [review]
